import type { Metadata } from "next";
import { AppProviders } from "@/libs/providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "BimeBazar",
  description: "Generated by Amir Ali Azimloo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
